command:
  - python
  - app.py
  - $DATABRICKS_APP_PORT

env:
  - name: GOVERNANCE_BACKEND
    value: databricks_sql
  - name: GOVERNANCE_CATALOG
    value: venus_forge_dev
  - name: GOVERNANCE_SCHEMA
    value: app_product_details
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql_warehouse
