command:
  - python
  - app.py
  - $DATABRICKS_APP_PORT

env:
  - name: GOVERNANCE_LAKEBASE_SCHEMA
    value: governance_app_v3
  - name: GOVERNANCE_ADMIN_EMAILS
    value: kerem.seyid@syngenta.com,harish.krishnamoorthy@syngenta.com
  - name: GOVERNANCE_NOTIFICATION_TEST_RECIPIENT
    value: kerem.seyid@syngenta.com
  - name: DATABRICKS_POSTGRES_ENDPOINT
    valueFrom: governance-lakebase
